theme: jekyll-theme-leap-day
title: [GitHub-OSS Fixit]
description: [Fixing bugs at scale in a Software Engineering Course]
show_downloads: ["false"]
# Google Analytics
google_analytics: UA-191730699-1
